retrieve microseconds

diff --git a/sort/tmren b/sort/tmren
--- a/sort/tmren
+++ b/sort/tmren
@@ -29,14 +29,39 @@ if [[ "$dryrun" == "no" ]]; then
     fi
 fi
 
+function getts()
+{
+    TS="$(stat --format="%y" "${1}" 2>/dev/null)"
+    if [[ $? -ne 0 ]]; then
+        TS="$(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S.000000" "${1}" 2>/dev/null)"
+        if [[ $? -ne 0 ]]; then
+            return 1
+        fi
+    fi
+
+    # 2025-06-04 23:28:47.051574355 +0900
+    # 0    5  8  11 14 17 20
+    YEAR=${TS:0:4}
+    MON=${TS:5:2}
+    DAY=${TS:8:2}
+    HOUR=${TS:11:2}
+    MIN=${TS:14:2}
+    SEC=${TS:17:2}
+    MIC=${TS:20:6}
+    echo "${YEAR}${MON}${DAY}-${HOUR}${MIN}${SEC}-${MIC}"
+}
+
 # Process each file in the directory
 find "$directory" -type f -print0 | while IFS= read -r -d '' fpath; do
     fname="$(basename "$fpath")"
     dpath="$(dirname "$fpath")"
 
     # Get the modification timestamp
-    timestamp="$(stat --format="%Y" "$fpath")"
-    timestamp="$(date --date="@${timestamp}" +%Y%m%d-%H%M%S)"
+    timestamp="$(getts "${fpath}")"
+    if [[ $? -ne 0 ]]; then
+        echo "Failed to get a timestamp for ${fpath}" 1>&2
+        continue
+    fi
 
     # Get the file extension
     extension="${fname##*.}"
